repos:
- repo: local
  hooks:
  - id: writemetadata
    name: writemetadata
    entry: py writemetadata.py
    language: system
    types: [python]
    pass_filenames: false
  - id: pipreqs_sorted
    name: pipreqs_sorted
    entry: py pipreqs_sorted.py
    language: system
    types: [python]
    pass_filenames: false
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
    args: [--safe]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8