import configparser

cfg = configparser.ConfigParser()
cfg.read("setup.cfg")

lines = ["# this file is autogenerated on pre-commit"]

lines.append('__version__ = "' + cfg["metadata"]["version"] + '"')
lines.append("")

open("src/x2df/__metadata__.py", "w").write("\n".join(lines))
